---
- name: Install the latest version of Git
  yum:
    name: git
    state: latest

- name: Install Java 11
  yum:
    name: java-11-openjdk.x86_64
    state: present

- name: Install Jenkins
  block:
    - name: Create Jenkins User
      user:
        name: jenkins
        comment: Jenkins Service User
        shell: /bin/false
    - name: Create Jenkins home directory
      file:
        path: /var/lib/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: Create Jenkins app directory
      file:
        path: /usr/lib/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: Create Jenkins log directory
      file:
        path: /var/log/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: Create Jenkins webroot directory
      file:
        path: /var/cache/jenkins/war
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes 
    - name: Copy Jenkins WAR from Cloud Storage
      shell: gsutil cp gs://jenkins-build-files/jenkins.war /usr/lib/jenkins/
    - name: Set permissions on Jennkins WAR
      file:
        path: /usr/lib/jenkins/jenkins.war
        owner: jenkins
        group: jenkins
        mode: 0777
    - name: Restore Jenkins configuration
      script: restore-jenkins.sh
    - name: Copy Jenkins configuration backup script
      copy:
        src: backup-jenkins.sh
        dest: /etc/cron.hourly/backup-jenkins.sh
        owner: jenkins
        group: jenkins
        mode: 0755
    - name: Create Jenkins Systemd Service
      copy:
        src: jenkins.service
        dest: /etc/systemd/system/jenkins.service
        owner: root
        group: root
        mode: 0644
    - name: Enable and Start the Jenkins Service
      service:
        enabled: yes
        state: restarted
        name: jenkins

- name: Install Nginx
  block:
    - name: Copy Nginx installer from GCS
      shell: gsutil cp gs://jenkins-build-files/nginx-1.16.1-1.el7.ngx.x86_64.rpm .
    - name: Install Nginx from local RPM
      yum:
        name:  nginx-1.16.1-1.el7.ngx.x86_64.rpm
        state: present      
    - name: Create Nginx log directory
      file:
        path: /var/log/nginx/jenkins
        state: directory
        owner: root
        group: root
        recurse: yes
    - name: Clean NGINX configuration
      file:
        state: absent
        path: /etc/nginx/conf.d/default.conf
    - name: Copy NGINX configuration
      copy:
        src: nginx.default.conf
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
    - name: Set httpd_t to permissive in SELINUX
      selinux_permissive:
        name: httpd_t
        permissive: true
    - name: Enable and Start the NGINX Service
      service:
        enabled: yes
        state: reloaded
        name: nginx

- name: Install PIP
  easy_install:
    name: pip
    state: latest

- name: Install Ansible
  pip:
    name:
      - ansible
      - pywinrm
    extra_args: --ignore-installed

- name: Set permissions on Python 2.7 modules directory
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
  with_items:
    - /usr/lib/python2.7/site-packages
    - /usr/lib64/python2.7/site-packages

- name: Set permissions on Ansible executables
  block:
    - name: Find Ansible executables
      find:
        paths: /usr/bin
        patterns: ansible*
      register: ansible_exes
    - name: Set permissions on Ansible executables
      file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: 0755
      with_items: "{{ ansible_exes.files }}"

- name: Install JQ
  yum:
    name: jq
    state: latest
  
- name: Install Unzip
  yum:
    name: unzip
    state: latest

- name: Install Packer
  block:
    - name: Copy Packer from Cloud Storage
      command: gsutil cp gs://jenkins-build-files-mq/packer_1.4.5_linux_amd64.zip /tmp
    - name: Extract Packer
      unarchive:
        src: /tmp/packer_1.4.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755

- name: Install Terraform
  block:
    - name: Copy Terraform from Cloud Storage
      command: gsutil cp gs://jenkins-build-files/terraform_0.12.16_linux_amd64.zip /tmp
    - name: Extract Terraform
      unarchive:
        src: /tmp/terraform_0.12.16_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: 0755

- name: Install Terraform plugins
  block:
    - name: Copy Terraform plugins from Cloud Storage
      command: gsutil cp gs://jenkins-build-files/terraform-provider-*.zip /tmp
    - name: Create Terraform plugins directory
      file:
        path: /home/jenkins/.terraform.d/plugins
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: Find Terraform plugin archives
      find:
        paths: /tmp
        patterns: terraform-provider-*.zip
      register: tf_plugins_archives
    - name: Extract Terraform plugins to plugins directory
      unarchive:
        src: "{{ item.path }}"
        dest: /home/jenkins/.terraform.d/plugins
        remote_src: yes
      with_items: "{{ tf_plugins_archives.files }}"
    - name: Find Terraform plugins
      find:
        paths: /home/jenkins/.terraform.d/plugins
        patterns: terraform-provider-*.zip
      register: tf_plugins
    - name: Set permissions on Terraform plugins
      file:
        path: "{{ item.path }}"
        owner: jenkins
        group: jenkins
        mode: 0755
      with_items: "{{ tf_plugins.files }}"

- name: Cleanup /tmp
  block:
    - name: Find items in /tmp
      find:
        paths: /tmp
        patterns: "*"
      register: tmp_files
    - name: Remove items in /tmp
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ tmp_files.files }}"

- name: Reset Permissions on Jenkins Home
  file:
    path: /var/lib/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Restart the Jenkins Service
  service:
    enabled: yes
    state: restarted
    name: jenkins
